package equcyph;

import java.awt.Color;
import java.util.HashMap;

/**
 *
 * @author hexaredecimal
 */
public class Properties extends javax.swing.JFrame {

	/**
	 * Creates new form Properties
	 */
	public Properties(EquCyph parent, Plane plane, int index, Function func) {
		initComponents();
		this.plane = plane; 
		this.index = index;
		this.parent = parent;
		
		tf_fx_def.setText(func.getDefinition());
		tf_fx_name.setText(func.getName());
    setLocation(new java.awt.Point(300, 400));
    setResizable(false);
		
		String[] awt_colors = {"BLACK", "BLUE", "CYAN", "DARK_GRAY", "GRAY", "GREEN", "LIGHT_GRAY", "MAGENTA", "ORANGE", "PINK", "RED", "WHITE", "YELLOW"};
		for (String color : awt_colors) {
			cb_colors.addItem(color);
			Color value = this.getColorFromString(color);
			colortable.put(color, value);
		}

	}

	private Color getColorFromString(String col) {
		switch (col.toLowerCase()) {
			case "black":
				return Color.BLACK;
			case "blue":
				return Color.BLUE;
			case "cyan":
				return Color.CYAN;
			case "darkgray":
				return Color.DARK_GRAY;
			case "gray":
				return Color.GRAY;
			case "green":
				return Color.GREEN;
			case "yellow":
				return Color.YELLOW;
			case "lightgray":
				return Color.LIGHT_GRAY;
			case "magneta":
				return Color.MAGENTA;
			case "orange":
				return Color.ORANGE;
			case "pink":
				return Color.PINK;
			case "red":
				return Color.RED;
			case "white":
				return Color.WHITE;
		}
		return Color.BLACK;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    tf_fx_name = new javax.swing.JTextField();
    cb_colors = new javax.swing.JComboBox<>();
    jLabel2 = new javax.swing.JLabel();
    btn_cancel = new javax.swing.JButton();
    btn_apply = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel3 = new javax.swing.JLabel();
    tf_fx_def = new javax.swing.JTextField();
    lbl_error = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Properties");

    jLabel1.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
    jLabel1.setText("Function Name");

    jLabel2.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
    jLabel2.setText("Color");

    btn_cancel.setText("Cancel");
    btn_cancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_cancelActionPerformed(evt);
      }
    });

    btn_apply.setText("Apply");
    btn_apply.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_applyActionPerformed(evt);
      }
    });

    jLabel3.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
    jLabel3.setText("Function Definition");

    lbl_error.setForeground(new java.awt.Color(255, 51, 51));
    lbl_error.setText("*");
    lbl_error.setEnabled(false);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lbl_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jSeparator1)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(tf_fx_name)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cb_colors, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(tf_fx_def)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(btn_apply)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_cancel)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(tf_fx_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(tf_fx_def, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cb_colors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lbl_error)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_cancel)
          .addComponent(btn_apply))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
    this.dispose();
  }//GEN-LAST:event_btn_cancelActionPerformed

  private void btn_applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_applyActionPerformed
    // TODO add your handling code here:
    var function = plane.getFunctionList().get(index);
    String colorString = String.valueOf(cb_colors.getSelectedItem());
    Color color = colortable.get(colorString);
		
		String name = tf_fx_name.getText(); 

		if (name.isBlank()) {
			lbl_error.setEnabled(true);
			lbl_error.setText("Missing function name");
			return;
		}

		String def = tf_fx_def.getText(); 
		if (def.isBlank()) {
			lbl_error.setEnabled(true);
			lbl_error.setText("Missing function definition");
			return;
		}

		lbl_error.setEnabled(false);
		lbl_error.setText("*");
		
		plane.getFunctionList().remove(function);
		plane.repaint();
		//function.setName(name);
		//function.setDefinition(def);
		//function.setColor(color);
		//plane.plot(function);
		parent.plotFunction(name, def, color);
		this.dispose();
  }//GEN-LAST:event_btn_applyActionPerformed

	private HashMap<String, Color> colortable = new HashMap<>();
	private int index; 
	private Plane plane; 
	private EquCyph parent; 
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_apply;
  private javax.swing.JButton btn_cancel;
  private javax.swing.JComboBox<String> cb_colors;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JLabel lbl_error;
  private javax.swing.JTextField tf_fx_def;
  private javax.swing.JTextField tf_fx_name;
  // End of variables declaration//GEN-END:variables
}
